dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 
      
install:
  - git clone https://github.com/open-source-parsers/jsoncpp.git
  - pushd jsoncpp
  - cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON 
  - sudo cmake --build .
  - popd

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .
