dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 
      - libwebsockets-dev
      
install:
  - git clone https://github.com/open-source-parsers/jsoncpp.git
  - pushd jsoncpp
  - cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON 
  - sudo make install
  - popd
  - cat /usr/include/libwebsockets.h

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .
